# Generated by Django 4.0.5 on 2022-06-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_post_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
